services:
  app:
    build:
      context: ./App
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      - ./App:/app
      - /app/node_modules
    environment:
      - EXPO_DEBUG=true
    tty: true
    command: npm start
  api:
    build:
      context: ./Api
    ports:
      - "3000:3000"
    volumes:
      - ./Api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev